services:
  mongodb:
    image: mongo:7.0
    container_name: 5thgate-backend-template-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: base_api
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
